# Homework : 3 Machine Learning - 1 (Supervised Methods)

## 4. Code up a 2-class perceptron learning algorithm and classifier.

### Importing Necessary Libraries

In [1]:
#Importing Libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Importing the nearestMeansClassifier library from utils package.
from utils import  perceptron

### Loading the Training Data and Testing Data from dataset-1 using Pandas

In [2]:
train_data_1 = pd.read_csv("./HW3_datasets/dataset1_train.csv", header=None)
print("Train Data -> 1: ")
print(train_data_1.head())
print()

test_data_1 = pd.read_csv("./HW3_datasets/dataset1_test.csv", header=None)
print("Test Data -> 1: ")
print(test_data_1.head())

Train Data -> 1: 
          0         1    2
0  2.199291  3.690399  1.0
1  0.472634 -0.709271  2.0
2 -0.026662 -1.335827  2.0
3 -0.116866 -1.336345  2.0
4  2.100909  1.143771  2.0

Test Data -> 1: 
          0         1    2
0  1.226845  0.273791  2.0
1 -0.929775  0.300098  1.0
2  0.220924  0.835073  1.0
3  0.783772 -0.233020  2.0
4  2.116507  0.728805  2.0


### Loading the Training Data and Testing Data from dataset-2 using Pandas

In [3]:
train_data_2 = pd.read_csv("./HW3_datasets/dataset2_train.csv", header=None)
print("Train Data -> 2: ")
print(train_data_2.head())
print()

test_data_2 = pd.read_csv("./HW3_datasets/dataset2_test.csv", header=None)
print("Train Data -> 2: ")
print(test_data_2.head())
print()

Train Data -> 2: 
          0         1    2
0  0.493655  0.905948  1.0
1  0.872053 -0.355721  2.0
2 -0.009021  0.132694  2.0
3 -0.578481  1.000596  1.0
4 -0.438395  1.038901  1.0

Train Data -> 2: 
          0         1    2
0 -0.070044 -0.118457  2.0
1 -0.824375  0.892066  1.0
2  1.384810  0.016317  2.0
3  0.304828  0.286498  2.0
4  1.651588  0.902572  1.0



### Loading the Training Data and Testing Data from dataset-3 using Pandas


In [4]:
train_data_3 = pd.read_csv("./HW3_datasets/dataset3_train.csv", header=None)
print("Train Data -> 3: ")
print(train_data_3.head())
print()

test_data_3 = pd.read_csv("./HW3_datasets/dataset3_test.csv", header=None)
print("Train Data -> 3: ")
print(test_data_3.head())

print()

Train Data -> 3: 
          0         1    2
0 -3.182181  1.966441  1.0
1  0.245498  1.287367  2.0
2  0.480500  0.785206  2.0
3  0.338015 -0.906211  1.0
4  0.396452  1.345380  2.0

Train Data -> 3: 
          0         1    2
0  0.624833  1.394105  2.0
1  2.976187 -0.119177  1.0
2  0.489271 -2.653542  1.0
3  0.159336  1.642712  2.0
4  0.059028  0.772479  2.0



In [5]:
perceptron_1 = perceptron.Perceptron()

In [6]:
n_train, X_train, T_train = perceptron_1.generateTrainData(trainData=train_data_1)
X_train_augmented = perceptron_1.augmentTrainData(X_train=X_train)
print(f"Shape of Augmented X_train: {X_train_augmented.shape}")

T_train_changed = perceptron_1.changeLabels(T_train=T_train)

X_train_shuffled, T_train_shuffled = perceptron_1.shuffleTrainData(X_train=X_train_augmented, T_train=T_train_changed.reshape(n_train, 1))

w_vector = perceptron_1.initializeWeights(0.1)

---------------------------------------------------
  Shape of Input Data: (100, 3)
  Number of Data Points: 100
  Number of Input Features: 2
  Number of Target Classes: 2
---------------------------------------------------
Shape of Augmented X_train: (100, 3)


In [7]:
X_train_shuffled[0:10]

array([[ 1.        , -0.8194963 , -1.42969518],
       [ 1.        ,  1.72628644,  0.81140485],
       [ 1.        , -0.11686633, -1.33634513],
       [ 1.        , -1.31467374, -0.2284476 ],
       [ 1.        , -0.22111103,  0.66801655],
       [ 1.        , -0.56729058,  0.64096728],
       [ 1.        ,  1.13416337,  1.95359901],
       [ 1.        ,  1.81865528,  1.01009377],
       [ 1.        ,  0.87039876,  1.86493455],
       [ 1.        ,  2.19929132,  3.69039929]])

In [8]:
T_train_shuffled[0:10]

array([[ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.]])

In [11]:
m, J_History, w_History = perceptron_1.modelTrain_SequentialGD(n_train = n_train, X_train=X_train_shuffled, T_train=T_train_shuffled, w_vector=w_vector, epochs=10000, learn_rate=1)
optimum_index = np.argmin(J_History)
w_optimum = w_History[optimum_index]

Y_hat = perceptron_1.predict(X=X_train_augmented, w_vector=w_optimum)
print(perceptron_1.calculateAccuracy(T_train, Y_hat=Y_hat))

1
[[-7.91459471]
 [-4.70253832]
 [-4.41916694]
 [-5.49894205]
 [-3.87056128]
 [-6.06626987]
 [-4.16336361]
 [-4.79890487]
 [-4.45773559]
 [-6.98559551]
 [-5.47280642]
 [-5.72976835]
 [-6.63119011]
 [-6.13896628]
 [-5.05348888]
 [-6.51366578]
 [-4.27378982]
 [-5.43533621]
 [-5.71680194]
 [-3.52984659]
 [-4.93365213]
 [-5.37539681]
 [-4.74165503]
 [-4.77262655]
 [-5.05169678]
 [-4.47626649]
 [-5.89497846]
 [-4.88445278]
 [-5.83046987]
 [-4.29869362]
 [-4.99385954]
 [-4.41124827]
 [-5.21741495]
 [-7.16635785]
 [-5.76574688]
 [-5.04773728]
 [-4.53768683]
 [-6.44301739]
 [-6.34921049]
 [-6.16737632]
 [-5.11887144]
 [-3.03009693]
 [-7.27054418]
 [-6.06574783]
 [-4.81095131]
 [-5.49269022]
 [-4.20464038]
 [-6.33590487]
 [-5.39133203]
 [-6.61273821]
 [ 2.69061729]
 [ 2.89498663]
 [ 3.43492008]
 [ 2.8584614 ]
 [ 4.20702935]
 [ 3.24717711]
 [ 4.26708319]
 [ 1.58758662]
 [ 3.48409261]
 [ 4.13656622]
 [ 2.71819291]
 [ 4.93588565]
 [ 4.1849797 ]
 [ 3.79802185]
 [ 2.73427005]
 [ 3.0695972 ]
 [ 4.921

In [12]:
w_optimum

array([[-0.9       ],
       [ 4.26541028],
       [-4.44273728]])